# Generated by Django 4.1 on 2023-11-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image_file", models.ImageField(upload_to="images/original/")),
                ("encrypted_image", models.ImageField(upload_to="images/encrypted/")),
                ("is_encrypted", models.BooleanField(default=False)),
                (
                    "encryption_key",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
        ),
    ]
