# Generated by Django 4.1 on 2023-11-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AES1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="decrypted_image",
            field=models.ImageField(default=0, upload_to="images/decrypted/"),
            preserve_default=False,
        ),
    ]
