# Generated by Django 4.1 on 2023-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AES1", "0002_image_decrypted_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="decryption_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
