# Generated by Django 4.1 on 2023-11-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AES1", "0003_image_decryption_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="aes_mode",
            field=models.CharField(default="ecb", max_length=10),
        ),
    ]
