# Generated by Django 4.1 on 2023-11-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AES1", "0004_image_aes_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="encryption_iv",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
